### PR TITLE
Media Type Converter updates - needs review

### LINKED ISSUE #63: StringBuilderStream for serialization tests?
Mark, what do you think about switching to a stream class that auto memo-izes the data written to it to a string, and makes that data available via a 'WrittenContent' string value?

### PR DESCRIPTION
**Pull request by EddieGarmon**
StringBuilderStream impl and cleaned up tests. 
Closes #63

Add IMediaConverter and ExplicitXmlConverter

### CODE REVIEW

**Comment by EddieGarmon** [comment]
There is still currently a failure when WriteView renders a razor page with just a handler and no model.

**Comment by EddieGarmon** [comment]
Mark, I believe its ready for review now. I also cleaned up the DataContractSerializer too.

**Comment by EddieGarmon** [comment]
Think this base type implementation is a better design, and fits with the json converters (yet to be done). It adds consistency in handling IOutput<T> that is IEnumerable<T>. Thoughts?

**Comment by EddieGarmon** [comment]
Also, the project Simple.Web.HalJson seems redundant as it has no tests/nuspec and almost identical code in Simple.Web.JsonNet. Should this be nuked?

**Comment by ThatRendle** [comment]
OK, all looks mostly good, I tweaked a couple of things in my own commit, with comments, but similar things should probably be done with the Write methods as well.

I'd love to see some A/B testing with DataContract vs Explicit and throughput metrics, if you've got any. I'd expect the Explicit to be a shit-load faster, but it would be nice to have the actual numbers.

Generally very happy though, crack on!

**Comment by ThatRendle** [comment]
Oh, and StringBuilderStream is much better than NonClosingMemoryStream.

**Pull request merged**
