### PR TITLE
Castle Windsor Support

### PR DESCRIPTION
**Pull request by mickdelaney**
Hi Guys,

I've knocked out support for Windsor. 
I've got it working in a sample fork of mark's bed & broadband here:
https://github.com/mickdelaney/BedAndBroadband

I wanted to look at integrating it with my mvc 4 app next. 
I guess owin would be the way to go there??

Regards

### CODE REVIEW

**Comment by ianbattersby** [comment]
Awesome! I know nothing of Castle Windsor in real world usage. My only feedback would be;
- Project files should include (link) CommonAssemblyInfo to Properties\AssemblyInfo.cs.
- Projects should ideally target 4.0 unless not able.
- You could include a nuspec file under /packaging also? 
- Worth squashing your commits, although we can do this when pulling in if needs be.

AwesomeSauce :-)

**Comment by ianbattersby** [comment]
Oh and yes, Owin integration would like be the way to go IMHO, although I'm not sure of the status of MS MVC and OWIN, suspect you'd need to stick with SystemWeb.

**Comment by mickdelaney** [comment]
ok, i'll sort out those issues, hopefully today but could be mid week.

**Comment by ianbattersby** [comment]
Sweet! @markrendle may have some comments too :)

**Comment by mickdelaney** [comment]
guys, i'd didnt follow the guidelines to the letter, i.e. didnt work in my own branch. 
will do in future, but i've not updated/amended anything, just added the 2 projects. 
in future i'll be a bit smarter about how i work!! :-)

**Comment by ianbattersby** [comment]
No worries, appreciate the effort!

When @markrendle is happy I'm probably going to grab your branch remotely and squash it down without the merges as it's got a bit mixed up here IMHO. Don't worry, the resulting one commit will still be in your name.

@markrendle: Don't press "Merge", just shout me for git fun-times :-)

**Comment by ianbattersby** [comment]
I've moved this to it's own [feature-branch](https://github.com/markrendle/Simple.Web/tree/feature-windsor) where we can review it without the merges and work on any required Mono support.

@mickdelaney You might want to update your remote so you can work on this branch from now on, and perhaps reset your master branch back to upstream/master.

https://github.com/markrendle/Simple.Web/tree/feature-windsor

**Comment by mickdelaney** [comment]
Yeah cool, will sort out the rebasing etc next time.

**Comment by ianbattersby** [comment]
FYI; This is [failing on the mono build](http://simpleci.cloudapp.net/viewLog.html?buildId=427&tab=buildResultsDiv&buildTypeId=bt7) as [Mono doesn't implement `CallContext.LogicalGetData`](https://github.com/mono/mono/blob/master/mcs/class/corlib/System.Runtime.Remoting.Messaging/CallContext.cs#L80) called [here](https://github.com/castleproject/Windsor/blob/master/src/Castle.Windsor/MicroKernel/Lifestyle/Scoped/CallContextLifetimeScope.cs#L136). We probably need to think how we are going to handle packages that aren't (perhaps ever) going to be mono compatible, especially as I can't see this on Xamarin's bugzilla.

https://github.com/mono/mono/blob/master/mcs/class/corlib/System.Runtime.Remoting.Messaging/CallContext.cs#L80

**Comment by ianbattersby** [comment]
@mickdelaney I notice looking at the Windsor code this wouldn't be an issue with v2.5.4, but you lose scoped lifestyles (e.g. `BeginScope()`) so not sure if this is feasible for you? .. or even being tied to v2.5.4? Perhaps raise an issue on [their GitHub](https://github.com/castleproject/Windsor) and see if they can help Mono guys implement it.

**Comment by ThatRendle** [comment]
All looks good, except you might want to replace Roy Jacobs's name with your own in the nuspec file.

Happy for Ian to merge after that, although if the Mono thing remains an issue...?

**Comment by ianbattersby** [comment]
I'd like to see what the Windsor guys say about Mono support, will raise an issue.

On a side note the build process replaces any nuspec value with a standard author tag, so I need to introduce something into rakefile which allows for custom contributor names against certain packages.

Will shout soon, hold onto your knickers for the moment :)

**Edit:** https://github.com/castleproject/Windsor/issues/31

**Comment by ianbattersby** [comment]
FYI; Have done the work to rakefile for custom contributor names and updated your name Mick (instead of Roy). Just waiting on an [indicator from Xamarin](https://bugzilla.xamarin.com/show_bug.cgi?id=14664) and I can squash and merge :)

**Comment by mickdelaney** [comment]
sorry guys been on a course all week so not had a chance to get on to the mono team.

**Comment by ianbattersby** [comment]
@mickdelaney No worries chap, I (unfortunately) do the 'mono buzgilla thing' many times a week at the moment, so thought I'd get it in there ready. Likely I'll merge this into master today as we don't want mono holding up your hard work :)

**Comment by mickdelaney** [comment]
thanks, that's great. i'd like mono support too to be honest. i'm not currently deploying web apps to linux but i do use it for other stuff, so am happy to start testing the windsor support on it in future.

**Comment by ianbattersby** [comment]
Merged. Opened a new issue to give sight to the mono issue. Thanks @mickdelaney!

**Pull request closed without merging**
