### PR TITLE
Feature media type handling

### PR DESCRIPTION
**Pull request by EddieGarmon**
Summary of changes: 
- Add MediaTypeHandlerBase that allows for separation of read/write wire format, object graph to/from wire format, custom link management for root items and collections.
- cleanup and merge HalJson into JsonNet, removed old HalJson projects 
- Xml and Json.Net handlers use this new base.
- Renamed the existing JsonMediaTypeHandler to JsonMediaTypeHandlerWithDeepLinks
- Cleaned up and organized the Solution file
- Added MediaTypeHandler performance test harness
- resolved merge conflicts from main in this branch

### CODE REVIEW

**Comment by ianbattersby** [comment]
@markrendle: I'll squash and merge this manually when ready, I wouldn't auto-merge it ;))

**Comment by ThatRendle** [comment]
OK, whenever you get a minute. I've been doing some cleanup on master, needs merging too then we can do a 0.10 release.

**Comment by ianbattersby** [comment]
FYI;
- Moved @EddieGarmon's commits to new branch [origin/feature-MediaTypeHandling](https://github.com/markrendle/Simple.Web/tree/feature-MediaTypeHandling). Suggest everybody checks I haven't missed something ;)
- Haven't squashed it yet, will do so when we are ready to merge into master.
- Removed Simple.Web.HalJson.Tests as assumed all these had moved to Simple.Web.JsonNet.Tests - @EddieGarmon ?

@markrendle: Feel free to push your changes to master and I'll rebase them in before merging above.

@EddieGarmon: Apologies if me moving it to a branch of our own causes you issues (naming it the same wasn't my greatest moment), but I REALLY want us to merge this with confidence we haven't (a) missed something (b) caused ourselves a merge-conflict hell.

PS. I just tried to merge your last additional commit and got all sorts of failures, will try again shortly.

**Comment by EddieGarmon** [comment]
@ianbattersby weird about the last commit. no idea. And I really don't care what the branch is named. I was just trying to be consistent, and will use "feature-XXX" in the future. May I suggest that we update the readme to provide this guidance? Well I guess I just did, huh? Why am I talking to myself?

Yes all the Hal stuff should be in the JsonNet and JsonNetTests libs now.

**Comment by EddieGarmon** [comment]
looks to me like a bunch of changes are missed

**Comment by ianbattersby** [comment]
Yep, I'm on it.

**Comment by ianbattersby** [comment]
@EddieGarmon Yes we need better instructions on pull-requests, quite honestly I probably didn't want to put people off when I wrote the origin README.md. Point taken though, apologies.

I have this branch now, let me know your thoughts, and if you want to proceed from there but want a different commit message before merging into master let me know.

https://github.com/markrendle/Simple.Web/tree/feature-MediaTypeHandling2

From my POV at least with one commit I can see the changes in one diff :)

**Comment by ianbattersby** [comment]
PS. Let me know if everyone is happy to lose the xml-updates branch now.

**Comment by ThatRendle** [comment]
Right, everything I've done is now pushed to master, and I promise I won't work on master anymore.

**Comment by ianbattersby** [comment]
MediaTypeHandling2 now compiles on Mono as well, and I fixed the mixed versions of JsonNet.

@EddieGarmon It would be wise to work against this branch now.

**Comment by EddieGarmon** [comment]
just cherry picked your fixes. I did see a few diffs between your MTH2 and the one i'm getting ready to pr

**Pull request closed without merging**
