### PR TITLE
Xml updates

### PR DESCRIPTION
**Pull request by EddieGarmon**
Added `IOutputEnumerable<TModel>` to support the generics based media type writing with an `IEnumerable<TModel> Output` property.

### CODE REVIEW

**Comment by EddieGarmon** [comment]
With the implementation of `IMediaTypeHandler { Task Write<T>(IContent content, Stream outputStream); }` the decision was that `T` should be `TModel`, and not `IEnumerable<TModel>`. All of the current work was to implement the `MediaTypeHandlerBase` with this in mind, and all tests are as such. 

This leads to an issue now where I must either wrap these enumerables (from GetCustomers() for example) in a CollectionDto just to support returning multiple resource representations, or use `IOutputEnumerable<T>` where I do not need to care about the CollectionDto at all.

NB: The xml media type handlers are currently the only implementation that actually use the <T> type information in their implementation. The json implementations still use content.Model.GetType() and pass that to their serializers.

**Comment by ThatRendle** [comment]
Hi, sorry, hope you didn't close this in despair at my failure to engage with it. Life is being a bit complicated for me lately.

I don't really like the IOutputEnumerable though, it seems there should be Another Way. I'll have a hack when I get time.

**Comment by ianbattersby** [comment]
I checked with Eddie on Twitter, GitHub did it when he moved branches I believe, we are still all good.

I'm still -1 on the suggestion too though, but I am happy to be convinced otherwise :-)

**Comment by EddieGarmon** [comment]
I renamed my branch, and GitHub decided I didn't want to contribute anymore.

My plan is to clean up all the MediaTypeHandling, including Json handlers. I have found a few inefficiencies that  should be corrected. 

Maybe the name `IOutputEnumerable<T>` is bad, and `IOutputMany<T>` would be 'simpler', but in moving to TypeParameters for MediaTypeConversion, handling `IOutput<IEnumerable<X>>` it is impossible to determine X at compile time without weaving (that I know of). The real issue is if you are outputting a single root element, or multiple elements without a single root container. And I agree that Simple.Web should be simple **to use**, not necessarily on the inside.

I have also created a ReSharper structural search and replace to help migrate to this new pattern. 

*Side note: I believe that we should create and include a ReSharper .DotSettings file with the standards that we want to follow with formatting. The more hands that touch the code, the more differences in style I see.

**Comment by ThatRendle** [comment]
Could you help me out and point to the exact bit of the code that is affected by this? I'm not getting it, probably because I've got too much going on in my head atm.

**Comment by EddieGarmon** [comment]
[MediaTypeHandlerBase.cs](https://github.com/EddieGarmon/Simple.Web/blob/feature-MediaTypeHandling/src/Simple.Web/MediaTypeHandling/MediaTypeHandlerBase.cs)

`public Task Write<T>(IContent content, Stream outputStream)`

Here we are checking to see if we have `content.Model is IEnumerable<T>`, which it will never be if you declare `IOutput<IEnumerable<X>>`. `IOutputEnumerable<T>` resolves this by changing the type parameter to be the model type, not the enumerated type.

**Comment by ThatRendle** [comment]
Right, OK, obviously I hate the idea of dual IOutput interfaces; here's what I propose instead:

Add a new method to ISimpleContainerScope, `object Get(Type t);` so we don't need the generic T to create IConvertXmlFor.

Change IConvertXmlFor<T> to an abstract class XmlConverterFor<T>, which has this:

``` csharp
public interface IXmlConverter
{
    XElement ToXml(object obj);
}
public abstract class XmlConverterFor<TModel> : IXmlConverter
{
    public abstract TModel FromXml(XElement xml);

    public abstract XElement ToXml(TModel item);

    public XElement ToXml(object obj)
    {
        return ToXml((TModel)obj);
    }
}
```

With those two changes, it shouldn't be too hard to write the reflection code necessary to work out that for `IOutput<T>`, T is an `IEnumerable<U>` something (with a check to make sure it's not a string, of course), depend a `typeof(XmlConverterFor<>).MakeGenericType(typeof(U))` as `IXmlConverter`, and call the object overload of the ToXml method.

Ta dah.

**Comment by EddieGarmon** [comment]
I understand your opposition to dual output interfaces. Also, against your advise, i'm looking at ALL media type converters, not just xml. The json implementations are too slow.

I'm looking to remove the explicit `IConvertXmlFor` implementation in Simple.Web.Xml, and move it to a demo/sample project. Reason being that I have had to re-implement it in my project as I don't use `SimpleContainer` at all, and shouldn't feel forced to. This makes it more of a blueprint of how you could roll your own formatter. And a single fix here doesn't help all converters.

The `JsonNet.HalJsonMediaTypeHandler` already conforms to `MediaTypeHandlerBase`, and follows that the `JsonNet.JsonMediaTypeHandler` should be rewritten in this manner since Hal currently performs over 218% better.

And on to the point. Unfortunately this suggestion does not solve the issue at all. The issue is that in Line 31 in MediaTypeHandlerBase linked above, the if statement will _never_ evaluate to true when you have `IOutput<IEnumerable<Something>>`.

**Comment by ThatRendle** [comment]
It does solve the issue, and I've got 100% passing tests to prove it. Main changes in https://gist.github.com/markrendle/6528764 - obviously changes to all the DI container wrappers etc were required.

**Comment by ThatRendle** [comment]
Regarding JSON, the HAL code was seriously sub-optimal, doing horrible things with the link handling. I suspect the performance of the plain Json.NET serializer would look very different, although I'm prepared to be surprised.

**Comment by EddieGarmon** [comment]
here are the results of the side by side tests of all media type converters today, run on my machine

```
Creating Content

Testing ExplicitXml.Write<T> over 5000 iterations...
Average: 0.00035775088s

Testing DataContractXml.Write<T> over 5000 iterations...
Average: 0.00067855338s

Testing JsonNet.Write<T> over 5000 iterations...
Average: 0.00207701242s

Testing HalJsonNet.Write<T> over 5000 iterations...
Average: 0.00093737262s

Testing JsonFX.Write<T> over 5000 iterations...
Average: 0.0028220757s

Done
```
- updated with correct JsonFX result. I had a breakpoint on in the prior run.

**Comment by ThatRendle** [comment]
Ooh, interesting.

I can't see your MediaTypeHandlerBase implementation of HalJson, have you not pushed it?

**Comment by EddieGarmon** [comment]
There is not a test in the code base today that tests this, unless you added one.
All tests today are in the form:
`target.Write<Customer>(content, stream).Wait();`
a valid test would be of the form:
`target.Write<IEnumerable<Customer>>(content, stream).Wait();`

**Comment by EddieGarmon** [comment]
What happened to threaded comments? anyway...

Those test results are using your HalJson implementation. The `MediaTypeHandlerBase<JValue>` implementation is on par with your implementation, as it is just mostly moving code. Run the performance test console from your machine and post me the results :)
- I would love to learn to type one day soon, hopefully even in markdown syntax, bah @github WHY U NO FIX FOR ME?

**Comment by ThatRendle** [comment]
I changed PicksUpOrdersLinkFromCustomers to use `Write<IEnumerable<Customer>>` instead of `Write<Customer>`. It passed before and it passed after.

**Comment by ThatRendle** [comment]
```
Creating Content

Testing ExplicitXml.Write<T> over 5000 iterations...
Average: 0.0001551654s

Testing DataContractXml.Write<T> over 5000 iterations...
Average: 0.00030650158s

Testing JsonNet.Write<T> over 5000 iterations...
Average: 0.00057288742s

Testing HalJsonNet.Write<T> over 5000 iterations...
Average: 0.00023031488s

Testing JsonFX.Write<T> over 5000 iterations...
Average: 0.00122832222s

Done
```

I am ever so slightly horrified by that.

If we can get past this IOutput thing and get your MediaTypeHandlerBase integrated, I think that would be good...

**Comment by EddieGarmon** [comment]
Yes, I agree. I will look at what you did again, and see where I missed something.

I think the default Json.Net is slower because it is doing double tokenization, once for the serializer, then once again under the covers as JValue. I think going directly against JValue is the more efficient way. 

We can also cleanup the link writing, and make that a separate abstract method so that end users can easily just customize the format of the link(s) element.

For now JsonFX would be out of luck, as their token impl is internal.

**Comment by EddieGarmon** [comment]
I see what you did there...

```
                var enumerable = content.Model as IEnumerable;
                if (enumerable != null && typeof(T) != typeof(string))
```

**Comment by ThatRendle** [comment]
Formatting of the link objects is something I want to make per-application configurable too, if possible.

**Comment by EddieGarmon** [comment]
coolio, new pr coming soon

**Pull request closed without merging**
