### PR TITLE
IMediaTypeHandler updates and IConvertXmlFor first pass

### PR DESCRIPTION
**Pull request by EddieGarmon**

### CODE REVIEW

**Comment by ThatRendle** [comment]
So tempted to say "I'm not going to pull this" after all the work you've done. But no...

**Comment by ThatRendle** [comment]
Looks great at first read, I'll have a proper look in VS soon.

**Comment by EddieGarmon** [comment]
There is lots more cleanup that can happen in the media type handlers, for instance I didn't change any code that was using the IContext.Model.GetType() to determine the object type instead of using the supplied <T>.

Also, need to refactor and separate out DataContractSerializer and ExplicitXmlSerializer.

This branch should probably not be merged back to main until at least those and perf are evaluated.

**Comment by EddieGarmon** [comment]
and if you said no... I would have started SimpleWeb2 :facepunch: tehe

**Pull request merged**
